# Generated by Django 6.0.3 on 2026-03-31 09:03

import school.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0003_alter_course_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cpf",
            field=models.CharField(
                max_length=11, unique=True, validators=[school.validators.validate_cpf]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(
                max_length=100, validators=[school.validators.validate_name]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(
                max_length=13, validators=[school.validators.validate_phone_number]
            ),
        ),
    ]
